export interface Env {
  DB: D1Database;
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_WEBHOOK_SECRET?: string;
  ADMIN_CHAT_ID: string;
  EMPLOYEE_IDS?: string;
}

interface TgUser { id: number; first_name: string; last_name?: string; username?: string; }
interface TgMessage { message_id: number; from?: TgUser; chat: { id: number; type?: string }; text?: string; }
interface TgCallback { id: string; from: TgUser; message?: TgMessage; data?: string; }
interface TgUpdate { update_id: number; message?: TgMessage; callback_query?: TgCallback; }
interface TgResult<T> { ok: boolean; result?: T; description?: string; }

const API = "https://api.telegram.org/bot";
const APP_CSS = `
:root{color-scheme:dark;--bg:#0b1020;--card:#151c31;--card2:#1c2540;--text:#f6f7fb;--muted:#98a3bd;--accent:#55d98a;--danger:#ff667d;--blue:#5d8cff;--line:#29324d}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#0b1020,#0e1426);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",sans-serif}button,input,textarea,select{font:inherit}button{border:0}.app{max-width:760px;margin:0 auto;padding:18px 16px 34px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.brand{font-weight:800;font-size:22px}.sub{color:var(--muted);font-size:13px;margin-top:3px}.avatar{width:42px;height:42px;border-radius:14px;background:var(--card2);display:grid;place-items:center;font-weight:800}.screen{display:none}.screen.active{display:block}.card{background:rgba(21,28,49,.92);border:1px solid var(--line);border-radius:20px;padding:18px;margin:12px 0;box-shadow:0 12px 35px #0002}.hero{padding:22px}.title{font-size:26px;font-weight:850;line-height:1.05}.muted{color:var(--muted)}.grid{display:grid;gap:12px}.grid2{grid-template-columns:1fr 1fr}.btn{width:100%;padding:15px 16px;border-radius:16px;color:#fff;background:var(--card2);font-weight:750;cursor:pointer}.btn.primary{background:linear-gradient(135deg,#34c978,#65e29b);color:#07130c}.btn.blue{background:linear-gradient(135deg,#4d76f4,#6e9aff)}.btn.danger{background:#40202a;color:#ff9aaa}.btn.small{padding:11px 12px;font-size:14px}.btn:disabled{opacity:.45}.section-title{font-size:18px;font-weight:800;margin:22px 0 10px}.obj{display:flex;justify-content:space-between;gap:12px;align-items:center;text-align:left}.obj b{display:block}.obj span{display:block;color:var(--muted);font-size:13px;margin-top:4px}.report{display:block}.badge{display:inline-flex;padding:6px 9px;border-radius:999px;background:#26304b;color:#cbd4ea;font-size:12px;font-weight:700}.badge.ok{background:#153b2a;color:#7ef0aa}.badge.work{background:#302d16;color:#ffd76a}.row{display:flex;justify-content:space-between;gap:12px;margin:8px 0}.row span{color:var(--muted)}.photo-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.photo-box{background:#0d1324;border-radius:16px;overflow:hidden;border:1px solid var(--line)}.photo-box img{width:100%;aspect-ratio:1;object-fit:cover;display:block}.photo-box .cap{padding:8px 10px;font-size:12px;color:var(--muted)}.drop{border:1.5px dashed #425072;border-radius:18px;padding:18px;text-align:center}.drop input{display:none}.counter{font-size:14px;color:var(--muted);margin:10px 0}.sticky{position:sticky;bottom:10px;margin-top:18px}.nav{display:flex;gap:8px;margin-top:18px}.nav .btn{flex:1}.hidden{display:none!important}.toast{position:fixed;left:16px;right:16px;bottom:18px;background:#fff;color:#101522;padding:13px 15px;border-radius:14px;font-weight:700;display:none;z-index:10}.error{color:#ff8fa1}
@media(max-width:520px){.grid2{grid-template-columns:1fr}.title{font-size:24px}}
`;
const APP_HTML = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>House Cleaning</title><script src="https://telegram.org/js/telegram-web-app.js"></script><style>${APP_CSS}</style></head><body><div class="app"><div class="top"><div><div class="brand">House Cleaning</div><div class="sub" id="role">Загрузка…</div></div><div class="avatar" id="avatar">HC</div></div><div id="home" class="screen active"></div><div id="objects" class="screen"></div><div id="new" class="screen"></div><div id="reports" class="screen"></div><div id="detail" class="screen"></div><div id="admin" class="screen"></div><div id="toast" class="toast"></div></div><script>
const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
let ME=null, objects=[], currentReport=null;
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;'}[c]||c));
function toast(s){$('toast').textContent=s;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2200)}
async function api(path,opt={}){const headers={'X-Telegram-Init-Data':tg?.initData||''};if(opt.body && !(opt.body instanceof FormData)){headers['Content-Type']='application/json';opt.body=JSON.stringify(opt.body)}const r=await fetch(path,{...opt,headers:{...headers,...(opt.headers||{})}});const j=await r.json().catch(()=>({error:'Ошибка сервера'}));if(!r.ok)throw new Error(j.error||'Ошибка');return j}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0)}
function shell(title,sub,body){return '<div class="card hero"><div class="title">'+title+'</div><div class="muted" style="margin-top:8px">'+sub+'</div></div>'+body}
async function init(){try{ME=await api('/api/me');$('role').textContent=ME.isAdmin?'Администратор':'Кабинет клинера';$('avatar').textContent=(ME.first_name||'HC').slice(0,1).toUpperCase();renderHome()}catch(e){document.body.innerHTML='<div class="app"><div class="card"><b>Не удалось открыть приложение</b><div class="muted" style="margin-top:8px">'+esc(e.message)+'</div></div></div>'}}
function renderHome(){let admin=ME.isAdmin;$('home').innerHTML=shell('Добро пожаловать, '+esc(ME.first_name||'клинер'),'Здесь только самое нужное','<div class="grid"><button class="btn primary" onclick="startReport()">Новый фотоотчёт</button><button class="btn blue" onclick="loadReports()">Мои отчёты</button>'+(admin?'<button class="btn" onclick="loadAdmin()">Панель администратора</button>':'')+'</div>');show('home')}
async function startReport(){try{if(!objects.length)objects=(await api('/api/objects')).objects;$('objects').innerHTML=shell('Выберите объект','Один раз выберите объект — адрес подставится автоматически','<div class="grid">'+objects.map(o=>'<button class="btn obj" onclick="createReport('+o.id+')"><div><b>'+esc(o.name)+'</b><span>'+esc(o.address||'Адрес не указан')+'</span></div><span>›</span></button>').join('')+'</div><div class="nav"><button class="btn small" onclick="show(\'home\')">Назад</button></div>');show('objects')}catch(e){toast(e.message)}}
async function createReport(objectId){try{currentReport=await api('/api/reports',{method:'POST',body:{object_id:objectId}});renderNew()}catch(e){toast(e.message)}}
function renderNew(){let r=currentReport;$('new').innerHTML=shell('Фотоотчёт','Объект: <b>'+esc(r.object.name)+'</b><br>'+esc(r.object.address||'')+'<br><span class="badge work">В работе</span>','<div class="section-title">1. Фото ДО</div><div id="beforeGrid" class="photo-grid"></div><div class="drop"><label class="btn blue small">Добавить фото ДО<input id="beforeInput" type="file" accept="image/*" capture="environment" multiple onchange="uploadPhotos(\'before\',this.files)"></label><div class="counter" id="beforeCount">0 фото</div></div><div class="section-title">2. Фото ПОСЛЕ</div><div id="afterGrid" class="photo-grid"></div><div class="drop"><label class="btn blue small">Добавить фото ПОСЛЕ<input id="afterInput" type="file" accept="image/*" capture="environment" multiple onchange="uploadPhotos(\'after\',this.files)"></label><div class="counter" id="afterCount">0 фото</div></div><div class="section-title">Дополнительно</div><textarea id="defects" placeholder="Дефекты, комментарий (необязательно)" style="width:100%;min-height:90px;background:#0d1324;color:#fff;border:1px solid var(--line);border-radius:14px;padding:12px"></textarea><input id="expense" inputmode="decimal" placeholder="Расходы, ₽ (необязательно)" style="width:100%;margin-top:10px;background:#0d1324;color:#fff;border:1px solid var(--line);border-radius:14px;padding:13px"><div class="sticky"><button class="btn primary" onclick="finishReport()">Отправить отчёт</button><button class="btn danger small" style="margin-top:8px" onclick="cancelReport()">Отменить</button></div>');refreshPhotos();show('new')}
async function uploadPhotos(phase,files){if(!files?.length)return;try{for(const file of Array.from(files)){if(file.size>15*1024*1024)throw new Error('Фото больше 15 МБ');const fd=new FormData();fd.append('report_id',currentReport.report.id);fd.append('phase',phase);fd.append('photo',file);await api('/api/photos',{method:'POST',body:fd})}currentReport=await api('/api/reports/'+currentReport.report.id);refreshPhotos()}catch(e){toast(e.message)}}
async function hydratePhotos(){for(const img of document.querySelectorAll('img[data-photo-id]')){try{const r=await fetch('/api/photo/'+img.dataset.photoId,{headers:{'X-Telegram-Init-Data':tg?.initData||''}});if(r.ok)img.src=URL.createObjectURL(await r.blob())}catch{}}}
function refreshPhotos(){if(!currentReport)return;const r=currentReport.report;const b=(r.photos||[]).filter(x=>x.phase==='before'),a=(r.photos||[]).filter(x=>x.phase==='after');$('beforeCount').textContent=b.length+' фото';$('afterCount').textContent=a.length+' фото';$('beforeGrid').innerHTML=b.map(p=>'<div class="photo-box"><img data-photo-id="'+p.id+'" loading="lazy"><div class="cap">ДО</div></div>').join('');$('afterGrid').innerHTML=a.map(p=>'<div class="photo-box"><img data-photo-id="'+p.id+'" loading="lazy"><div class="cap">ПОСЛЕ</div></div>').join('');hydratePhotos()}
async function finishReport(){try{const defects=$('defects').value.trim();const expense=$('expense').value.trim();await api('/api/reports/'+currentReport.report.id,{method:'PATCH',body:{defects,expense_amount:expense?Number(expense):null,status:'completed'}});toast('Отчёт отправлен');setTimeout(()=>{currentReport=null;loadReports()},500)}catch(e){toast(e.message)}}
async function cancelReport(){if(!confirm('Отменить текущий отчёт? Фото и данные не удалятся.'))return;try{await api('/api/reports/'+currentReport.report.id,{method:'PATCH',body:{status:'cancelled'}});currentReport=null;show('home')}catch(e){toast(e.message)}}
async function loadReports(){try{const j=await api('/api/reports?mine=1');$('reports').innerHTML=shell('Мои отчёты','Все ваши фотоотчёты','<div class="grid">'+(j.reports.length?j.reports.map(r=>reportCard(r)).join(''):'<div class="card muted">Отчётов пока нет</div>')+'</div><div class="nav"><button class="btn small" onclick="show(\'home\')">Главное меню</button></div>');show('reports')}catch(e){toast(e.message)}}
function reportCard(r){return '<button class="btn report" style="text-align:left" onclick="loadDetail('+r.id+')"><div class="row"><b>'+esc(r.public_id)+'</b><span class="badge '+(r.status==='completed'?'ok':'work')+'">'+(r.status==='completed'?'Завершён':r.status==='cancelled'?'Отменён':'В работе')+'</span></div><div class="muted">'+esc(r.object_name)+'<br>'+esc(r.address||'')+'</div><div class="row" style="margin-top:10px"><span>До: '+r.before_count+'</span><span>После: '+r.after_count+'</span></div></button>'}
async function loadDetail(id){try{const j=await api('/api/reports/'+id);renderDetail(j.report,false)}catch(e){toast(e.message)}}
function renderDetail(r,admin){$('detail').innerHTML=shell(r.public_id,esc(r.object_name)+'<br>'+esc(r.address||''),'<div class="card"><div class="row"><span>Клинер</span><b>'+esc(r.cleaner_name)+'</b></div><div class="row"><span>Статус</span><b>'+esc(r.status)+'</b></div><div class="row"><span>Начало</span><b>'+esc(r.started_at_local)+'</b></div><div class="row"><span>Завершение</span><b>'+esc(r.completed_at_local||'—')+'</b></div><div class="row"><span>Дефекты</span><b>'+esc(r.defects||'Нет')+'</b></div><div class="row"><span>Расходы</span><b>'+esc(r.expense_amount?String(r.expense_amount)+' ₽':'Нет')+'</b></div></div><div class="section-title">Фото ДО / ПОСЛЕ</div><div class="photo-grid">'+(r.photos||[]).map(p=>'<div class="photo-box"><img data-photo-id="'+p.id+'" loading="lazy"><div class="cap">'+(p.phase==='before'?'ДО':'ПОСЛЕ')+'</div></div>').join('')+'</div><div class="nav"><button class="btn small" onclick="'+(admin?'loadAdmin()':'loadReports()')+'">Назад</button></div>');show('detail');hydratePhotos()}
async function loadAdmin(){if(!ME.isAdmin)return;try{if(!objects.length)objects=(await api('/api/objects')).objects;const j=await api('/api/admin/dashboard');$('admin').innerHTML=shell('Панель администратора','Все фотоотчёты в одном месте','<div class="grid grid2"><div class="card"><b>'+j.stats.today+'</b><div class="muted">Сегодня</div></div><div class="card"><b>'+j.stats.in_progress+'</b><div class="muted">В работе</div></div></div><div class="section-title">Отчёты</div><div class="grid">'+(j.reports.length?j.reports.map(r=>'<button class="btn report" style="text-align:left" onclick="adminDetail('+r.id+')"><div class="row"><b>'+esc(r.public_id)+'</b><span>'+esc(r.status)+'</span></div><div>'+esc(r.cleaner_name)+'</div><div class="muted">'+esc(r.object_name)+'<br>'+esc(r.address||'')+'</div><div class="row"><span>До: '+r.before_count+'</span><span>После: '+r.after_count+'</span></div></button>').join(''):'<div class="card muted">Нет отчётов</div>')+'</div><div class="section-title">Объекты</div><div class="grid">'+objects.map(o=>'<div class="card"><b>'+esc(o.name)+'</b><div class="muted">'+esc(o.address||'')+'</div></div>').join('')+'</div><div class="nav"><button class="btn small" onclick="show(\'home\')">Главное меню</button></div>');show('admin')}catch(e){toast(e.message)}}
async function adminDetail(id){try{const j=await api('/api/reports/'+id);renderDetail(j.report,true)}catch(e){toast(e.message)}}
init();
</script></body></html>`;

function isAdmin(env: Env, id: number): boolean { return Number(env.ADMIN_CHAT_ID?.trim()) === id; }
function isEmployee(env: Env, id: number): boolean { return isAdmin(env,id) || (env.EMPLOYEE_IDS??"").split(",").map(x=>Number(x.trim())).filter(Number.isFinite).includes(id); }
function localDate(s?: string|null): string { if(!s)return ""; return new Intl.DateTimeFormat("ru-RU",{timeZone:"Europe/Moscow",dateStyle:"short",timeStyle:"short"}).format(new Date(s)); }
function json(data: unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=UTF-8","cache-control":"no-store"}})}
function html(){return new Response(APP_HTML,{headers:{"content-type":"text/html;charset=UTF-8","cache-control":"no-store"}})}
async function hmac(keyBytes: ArrayBuffer|Uint8Array, data: string): Promise<ArrayBuffer>{const key=await crypto.subtle.importKey("raw",keyBytes,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return crypto.subtle.sign("HMAC",key,new TextEncoder().encode(data));}
function hex(buf:ArrayBuffer){return Array.from(new Uint8Array(buf)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function equal(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function verifyInitData(initData:string,token:string):Promise<TgUser>{if(!initData)throw new Error("Откройте приложение из Telegram");const p=new URLSearchParams(initData);const hash=p.get("hash")||"";p.delete("hash");const pairs=Array.from(p.entries()).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`);const secret=await hmac(new TextEncoder().encode(token),"WebAppData");const good=hex(await hmac(secret,pairs.join("\n")));if(!equal(good,hash))throw new Error("Недействительная сессия Telegram");const authDate=Number(p.get("auth_date"));if(!authDate||Date.now()/1000-authDate>24*60*60)throw new Error("Сессия Telegram устарела");const raw=p.get("user");if(!raw)throw new Error("Пользователь не найден");return JSON.parse(raw) as TgUser}
async function auth(req:Request,env:Env){return verifyInitData(req.headers.get("X-Telegram-Init-Data")||new URL(req.url).searchParams.get("initData")||"",env.TELEGRAM_BOT_TOKEN)}
async function ensureEmployee(env:Env,u:TgUser){await env.DB.prepare(`INSERT INTO employees (telegram_id,first_name,last_name,username,active) VALUES (?,?,?,?,1) ON CONFLICT(telegram_id) DO UPDATE SET first_name=excluded.first_name,last_name=excluded.last_name,username=excluded.username,active=1`).bind(u.id,u.first_name,u.last_name??null,u.username??null).run();}
async function listObjects(env:Env){const r=await env.DB.prepare(`SELECT id,name,address,latitude,longitude FROM objects ORDER BY name COLLATE NOCASE`).all();return r.results as any[]}
async function getReport(env:Env,id:number,u:TgUser){const r=await env.DB.prepare(`SELECT r.id,r.public_id,r.started_at,r.completed_at,r.status,o.id object_id,o.name object_name,o.address,e.telegram_id cleaner_id,e.first_name,e.last_name,e.username,(SELECT details FROM audit_log WHERE report_id=r.id AND action='report_meta' ORDER BY id DESC LIMIT 1) details FROM reports r JOIN objects o ON o.id=r.object_id JOIN employees e ON e.id=r.employee_id WHERE r.id=?`).bind(id).first<any>();if(!r)throw new Error("Отчёт не найден");if(!isAdmin(env,u.id)&&r.cleaner_id!==u.id)throw new Error("Нет доступа");const photos=await env.DB.prepare(`SELECT id,phase,telegram_file_id,created_at FROM report_photos WHERE report_id=? ORDER BY id`).bind(id).all();let meta:any={};try{meta=r.details?JSON.parse(r.details):{}}catch{}return {...r,cleaner_name:[r.first_name,r.last_name].filter(Boolean).join(" ")||r.username||String(r.cleaner_id),defects:meta.defects||"",expense_amount:meta.expense_amount??null,started_at_local:localDate(r.started_at),completed_at_local:localDate(r.completed_at),photos:photos.results};}
async function sendPhotoToTelegram(env:Env,chatId:number,file:File){const fd=new FormData();fd.append("chat_id",String(chatId));fd.append("photo",file,file.name||"report.jpg");const r=await fetch(`${API}${env.TELEGRAM_BOT_TOKEN}/sendPhoto`,{method:"POST",body:fd});const j=await r.json() as any;if(!j.ok)throw new Error(j.description||"Не удалось загрузить фото в Telegram");const m=j.result;const p=m.photo?.[m.photo.length-1];try{await fetch(`${API}${env.TELEGRAM_BOT_TOKEN}/deleteMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,message_id:m.message_id})})}catch{}return {file_id:p.file_id,file_unique_id:p.file_unique_id};}
async function apiHandler(req:Request,env:Env){const url=new URL(req.url);let u:TgUser;try{u=await auth(req,env)}catch(e){return json({error:(e as Error).message},401)}if(!isEmployee(env,u.id))return json({error:"У вас нет доступа к приложению"},403);await ensureEmployee(env,u);try{
if(url.pathname==="/api/me"&&req.method==="GET")return json({id:u.id,first_name:u.first_name,last_name:u.last_name,username:u.username,isAdmin:isAdmin(env,u.id)});
if(url.pathname==="/api/objects"&&req.method==="GET")return json({objects:await listObjects(env)});
if(url.pathname==="/api/reports"&&req.method==="GET"){const mine=url.searchParams.get("mine")==="1";const where=isAdmin(env,u.id)&&!mine?"":"AND e.telegram_id=?";const args:any[]=mine||!isAdmin(env,u.id)?[u.id]:[];const q=`SELECT r.id,r.public_id,r.started_at,r.completed_at,r.status,o.name object_name,o.address,e.telegram_id cleaner_id,e.first_name,e.last_name,e.username,(SELECT COUNT(*) FROM report_photos p WHERE p.report_id=r.id AND p.phase='before') before_count,(SELECT COUNT(*) FROM report_photos p WHERE p.report_id=r.id AND p.phase='after') after_count FROM reports r JOIN objects o ON o.id=r.object_id JOIN employees e ON e.id=r.employee_id WHERE 1=1 ${where} ORDER BY r.id DESC LIMIT 100`;const rows=await env.DB.prepare(q).bind(...args).all();return json({reports:(rows.results as any[]).map(r=>({...r,cleaner_name:[r.first_name,r.last_name].filter(Boolean).join(" ")||r.username||String(r.cleaner_id),started_at_local:localDate(r.started_at),completed_at_local:localDate(r.completed_at)}))});}
const rm=url.pathname.match(/^\/api\/reports\/(\d+)$/);if(rm){const id=Number(rm[1]);if(req.method==="GET")return json({report:await getReport(env,id,u)});if(req.method==="PATCH"){const body=await req.json() as any;const before=await getReport(env,id,u);const status=body.status||before.status;await env.DB.prepare(`UPDATE reports SET status=?,completed_at=CASE WHEN ?='completed' THEN COALESCE(completed_at,datetime('now')) ELSE completed_at END,updated_at=datetime('now') WHERE id=?`).bind(status,status,id).run();await env.DB.prepare(`INSERT INTO audit_log (telegram_id,action,report_id,details) VALUES (?,?,?,?)`).bind(u.id,"report_meta",id,JSON.stringify({defects:body.defects??before.defects??"",expense_amount:body.expense_amount??before.expense_amount??null})).run();return json({report:await getReport(env,id,u)});}}
if(url.pathname==="/api/reports"&&req.method==="POST"){const body=await req.json() as any;const obj=await env.DB.prepare(`SELECT id,name,address,latitude,longitude FROM objects WHERE id=?`).bind(Number(body.object_id)).first<any>();if(!obj)throw new Error("Объект не найден");const emp=await env.DB.prepare(`SELECT id FROM employees WHERE telegram_id=?`).bind(u.id).first<any>();const publicId='HC-'+crypto.randomUUID().slice(0,8).toUpperCase();const r=await env.DB.prepare(`INSERT INTO reports(public_id,employee_id,object_id,started_at,updated_at,status) VALUES(?,?,?,datetime('now'),datetime('now'),'in_progress')`).bind(publicId,emp.id,obj.id).run();await env.DB.prepare(`INSERT INTO audit_log(telegram_id,action,report_id,details) VALUES(?,?,?,?)`).bind(u.id,'report_meta',Number(r.meta.last_row_id),JSON.stringify({defects:'',expense_amount:null})).run();return json({report:await getReport(env,Number(r.meta.last_row_id),u),object:obj},201)}
if(url.pathname==="/api/photos"&&req.method==="POST"){const fd=await req.formData();const reportId=Number(fd.get('report_id'));const phase=String(fd.get('phase'));const file=fd.get('photo');if(!['before','after'].includes(phase)||!(file instanceof File))throw new Error('Неверные данные фото');const rr=await getReport(env,reportId,u);if(rr.status==='completed'||rr.status==='cancelled')throw new Error('Отчёт уже закрыт');const count=rr.photos.filter((p:any)=>p.phase===phase).length;if(count>=50)throw new Error('Максимум 50 фото на этап');const sent=await sendPhotoToTelegram(env,u.id,file);await env.DB.prepare(`INSERT INTO report_photos(report_id,phase,telegram_file_id,telegram_file_unique_id) VALUES(?,?,?,?)`).bind(reportId,phase,sent.file_id,sent.file_unique_id).run();return json({ok:true})}
const pm=url.pathname.match(/^\/api\/photo\/(\d+)$/);if(pm&&req.method==='GET'){const id=Number(pm[1]);const p=await env.DB.prepare(`SELECT p.telegram_file_id,e.telegram_id FROM report_photos p JOIN reports r ON r.id=p.report_id JOIN employees e ON e.id=r.employee_id WHERE p.id=?`).bind(id).first<any>();if(!p)return new Response('Not found',{status:404});if(!isAdmin(env,u.id)&&p.telegram_id!==u.id)return new Response('Forbidden',{status:403});const gf=await fetch(`${API}${env.TELEGRAM_BOT_TOKEN}/getFile?file_id=${encodeURIComponent(p.telegram_file_id)}`);const gj=await gf.json() as any;if(!gj.ok)return new Response('Photo unavailable',{status:404});const file=await fetch(`https://api.telegram.org/file/bot${env.TELEGRAM_BOT_TOKEN}/${gj.result.file_path}`);return new Response(file.body,{headers:{'content-type':file.headers.get('content-type')||'image/jpeg','cache-control':'private,max-age=300'}})}
if(url.pathname==="/api/admin/dashboard"&&req.method==='GET'){if(!isAdmin(env,u.id))return json({error:'Нет доступа'},403);const stats=await env.DB.prepare(`SELECT SUM(CASE WHEN date(r.started_at,'+3 hours')=date('now','+3 hours') THEN 1 ELSE 0 END) today,SUM(CASE WHEN r.status='in_progress' THEN 1 ELSE 0 END) in_progress FROM reports r`).first<any>();const rows=await env.DB.prepare(`SELECT r.id,r.public_id,r.status,r.started_at,o.name object_name,o.address,e.telegram_id cleaner_id,e.first_name,e.last_name,e.username,(SELECT COUNT(*) FROM report_photos p WHERE p.report_id=r.id AND p.phase='before') before_count,(SELECT COUNT(*) FROM report_photos p WHERE p.report_id=r.id AND p.phase='after') after_count FROM reports r JOIN objects o ON o.id=r.object_id JOIN employees e ON e.id=r.employee_id ORDER BY r.id DESC LIMIT 200`).all();return json({stats:{today:Number(stats?.today||0),in_progress:Number(stats?.in_progress||0)},reports:(rows.results as any[]).map(r=>({...r,cleaner_name:[r.first_name,r.last_name].filter(Boolean).join(' ')||r.username||String(r.cleaner_id)}))})}
return json({error:'Not found'},404);
}catch(e){return json({error:(e as Error).message||'Ошибка'},400)}}
async function telegramCall<T>(env:Env,method:string,payload:Record<string,unknown>):Promise<T>{const r=await fetch(`${API}${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json() as TgResult<T>;if(!j.ok)throw new Error(j.description||method);return j.result as T}
async function bot(env:Env,update:TgUpdate,base:string){const m=update.message,c=update.callback_query;if(c){await telegramCall(env,'answerCallbackQuery',{callback_query_id:c.id});if(c.data==='admin'&&isAdmin(env,c.from.id))await telegramCall(env,'sendMessage',{chat_id:c.from.id,text:'Панель администратора теперь находится в приложении. Нажмите кнопку ниже.',reply_markup:{inline_keyboard:[[{text:'📱 Открыть приложение',web_app:{url:base+'/app'}}]]}});return;}if(!m?.from||!isEmployee(env,m.from.id))return;if(m.text==='/start'||m.text==='/app'||m.text==='Меню'){await telegramCall(env,'sendMessage',{chat_id:m.chat.id,text:`<b>House Cleaning</b>\n\nВсе фотоотчёты теперь в удобном приложении.\nНажмите «Открыть приложение».`,parse_mode:'HTML',reply_markup:{inline_keyboard:[[ {text:'📱 Открыть приложение',web_app:{url:base+'/app'}} ], ...(isAdmin(env,m.from.id)?[[{text:'🛠 Панель администратора',callback_data:'admin'}]]:[]) ]}})}}
export default {async fetch(req:Request,env:Env):Promise<Response>{const url=new URL(req.url);if(url.pathname==='/health')return json({ok:true,service:'hcotcet',app:'/app'});if(url.pathname==='/app'&&req.method==='GET')return html();if(url.pathname.startsWith('/api/'))return apiHandler(req,env);if(url.pathname==='/webhook'&&req.method==='POST'){if(env.TELEGRAM_WEBHOOK_SECRET&&req.headers.get('x-telegram-bot-api-secret-token')!==env.TELEGRAM_WEBHOOK_SECRET)return new Response('Unauthorized',{status:401});const update=await req.json() as TgUpdate;try{await bot(env,update,`${url.origin}`)}catch(e){console.error(e)}return new Response('OK')}return new Response('Not found',{status:404})}};
